################################################################################
##                             Network interface                              ##
################################################################################
server:
  # Address to which we bind (default: 127.0.0.1)
  address: "${HOST_IP}"
  # Port on which we bind (default: 7070)
  port: "${HOST_PORT}"

################################################################################
##                               Database options                             ##
################################################################################
database:
  host: "${DATABASE_HOST}"
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  database: "${DATABASE_NAME}"
  scheme: "${DATABASE_SCHEME}"
  port: "${DATABASE_PORT}"
  connectionTimeoutMillis: 2000
  max: 100

graph:
  host: "${GRAPH_DATABASE_HOST}"
  user: "${GRAPH_DATABASE_USER}"
  password: "${GRAPH_DATABASE_PASSWORD}"
  database: "${GRAPH_DATABASE_NAME}"
  scheme: "${GRAPH_DATABASE_SCHEME}"
  port: "${GRAPH_DATABASE_PORT}"
  connectionTimeoutMillis: 2000
  max: 100

################################################################################
##                               Logging options                              ##
################################################################################
logging:
  # Values: error, warn, info, http, verbose, debug, silly
  level: http

################################################################################
##                             Scheduler options                              ##
################################################################################
scheduler:
  enable: true
  items:
    - name: approval
      enable: true
      expression: "*/3 * * * * *"
    - name: close
      enable: true
      expression: "*/10 * * * * *"
    - name: watch
      enable: true
      expression: "*/1 * * * * *"
    - name: purchase
      enable: true
      expression: "*/1 * * * * *"
    - name: delegatorApproval
      enable: true
      expression: "*/5 * * * * *"
    - name: metrics
      enable: true
      expression: "*/5 * * * * *"

relay:
  managerKeys:
    - "${CERTIFIER01}"
    - "${CERTIFIER02}"
    - "${CERTIFIER03}"
    - "${CERTIFIER04}"
    - "${CERTIFIER05}"
    - "${CERTIFIER06}"
    - "${CERTIFIER07}"
    - "${CERTIFIER08}"
    - "${CERTIFIER09}"
    - "${CERTIFIER10}"
  accessKey: "${ACCESS_KEY}"
  callbackEndpoint: "${CALLBACK_ENDPOINT}"
  callbackAccessKey: "${CALLBACK_ACCESS_KEY}"
  paymentTimeoutSecond: 45
  approvalSecond: 3
  forcedCloseSecond: 300
  expoAccessToken: "${EXPO_ACCESS_TOKEN}"
  relayEndpoint: "${RELAY_ENDPOINT}"
  encryptKey: "${RELAY_ENCRYPT_KEY}"

contracts:
  sideChain:
    network: "production_side"
    url: "${SIDE_CHAIN_RPC_URL}"
    ledgerAddress : "${LEDGER_CONTRACT_ADDRESS}"
    phoneLinkerAddress : "${PHONE_LINKER_CONTRACT_ADDRESS}"
    shopAddress : "${SHOP_CONTRACT_ADDRESS}"
    currencyRateAddress: "${CURRENCY_RATE_CONTRACT_ADDRESS}"
    loyaltyProviderAddress: "${LOYALTY_PROVIDER_CONTRACT_ADDRESS}"
    loyaltyConsumerAddress: "${LOYALTY_CONSUMER_CONTRACT_ADDRESS}"
    loyaltyExchangerAddress: "${LOYALTY_EXCHANGER_CONTRACT_ADDRESS}"
    loyaltyTransferAddress: "${LOYALTY_TRANSFER_CONTRACT_ADDRESS}"
    tokenAddress : "${TOKEN_CONTRACT_ADDRESS}"
    loyaltyBridgeAddress: "${SIDE_CHAIN_LOYALTY_BRIDGE_CONTRACT_ADDRESS}"
    chainBridgeAddress: "${SIDE_CHAIN_BRIDGE_CONTRACT_ADDRESS}"
  mainChain:
    network: "production_main"
    url: "${MAIN_CHAIN_RPC_URL}"
    tokenAddress : "${MAIN_CHAIN_TOKEN_CONTRACT_ADDRESS}"
    loyaltyBridgeAddress: "${MAIN_CHAIN_LOYALTY_BRIDGE_CONTRACT_ADDRESS}"
    chainBridgeAddress: "${MAIN_CHAIN_BRIDGE_CONTRACT_ADDRESS}"

metrics:
  accounts:
    - name: "finance"
      address: "0x4501F7aF010Cef3DcEaAfbc7Bfb2B39dE57df54d"
    - name: "settlement"
      address: "0x1Ea9d36d45A42C95A8752541Fa06047DEc482F89"
    - name: "fee"
      address: "0x6440665c7480451f28aE57A3d552DF3bA04383b1"
    - name: "txFee"
      address: "0x3633B7eBd5562316BD3740FAe1d5A4aD46DbD8f0"
